- hosts: apps
  tasks:
    - name: install python
      apt:
        name: python-docker
        state: present
    - name: run docker container
      docker_container:
        image: ariretiarno/demo
        detach: yes
        interactive: yes
        tty: yes
        name: apps
        state: running
        exposed_ports: 80
