- hosts: apps
  tasks:
    - name: install python
      apt:
        name: python-docker
        state: present
    - name: stop docker container
      docker_container:
        name: apps
        state: absent
    - name: rm image
      docker_image:
        name: ariretiarno/demo
        state: absent
    - name: run container
      docker_container:
        name: apps
        image: ariretiarno/demo
        detach: yes
        interactive: yes
        tty: yes
        name: apps
        state: started
        ports:
          - "80:80"
