- hosts: apps
  tasks:
    - name: install python
      apt:
        name: python-docker
        state: present
    - name: run docker container
      docker_container:
        image: ariretiarno/demo
        name: apps
        state: absent
